### ISSUE TITLE
How to write the descriptor for `anyof` classes  like Swagger

### ISSUE THREAD

**Issue by UkonnRa** [Kotlin/kotlinx.serialization#1249]
**What is your use-case and why do you need this feature?**

In swagger we can define some thing like:

```yaml
      anyOf:
        - type: string
        - type: object
          properties:
            href:
              type: string
            meta:
              type: object
```

The equivalent Kotlin code like this (using inline, not valid Kotlin code):

```kotlin
@Serializable
sealed class Links {
  @Serializable
  inline class Str(val value: String) : Links() // `inline` cannot be used here, just a example

  @Serializable
  data class Obj(val href: String, val meta: Meta?) : Links()
}
```

So class `Links` can be represented at both: **a string** or **an object**

Just wondering how to handle this using `kotlinx.serialization`?

**Describe the solution you'd like**

The situation above can be handled
