### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by uuf6429** [Kotlin/kotlinx.serialization#2509]
I've spent a ridiculous amount of time trying to set this up, with no success whatsoever.

Let's look at the instructions...
<img width="244" alt="image" src="https://github.com/Kotlin/kotlinx.serialization/assets/230049/400851d2-8ad2-4961-8205-b746dd86e38e">

To me that means that we either install it in gradle or in android, or in multiplatform...
Otherwise the headings do not make any sense. Maybe the headings should have been so:
- Gradle
   1. Setting up the serialization plugin
   2. Dependency on the json library
      - Android
      - Multiplatform
- Maven

??

Next, why is this library depending on a plugin? When do we need to install this plugin...is it optional or mandatory?

Why is "android" separate from "multiplatform"? Isn't android just another platform?

Looking at the instructions themselves... I have 3 `*.gradle.kts` files.. where should the setup settings go?

Sidenote: should end users of this library really care about the proguard stuff mentioned under "android" in the setup?

----

So in short (since I can't get android to compile and IDE completion fails randomly), what are the real instructions to use this in a KMP project?

**Comment by uuf6429** [comment]
After some trial and error, here's what seems to make it work (at least on android):

In `gradle/libs.versions.toml`, I have the following:
```toml
# under the [versions] section
jetbrains-kotlinxSerializationJson = "1.0.0"
jetbrains-kotlinxSerializationRuntime = "0.14.0"
kotlinxSerializationJson = "1.4.1"

# under the [libraries] section
jetbrains-kotlinx-serialization-runtime = { module = "org.jetbrains.kotlinx:kotlinx-serialization-runtime", version.ref = "jetbrains-kotlinxSerializationRuntime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# under the [plugins] section
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
```

And in `composeApp/build.gradle.kts`:
```kts
plugins {
// ...
    alias(libs.plugins.kotlinSerialization)     // <----
}

kotlin {
// ...

    sourceSets {
        val androidMain by getting {
            dependencies {
// ...
            }
        }
        val commonMain by getting {
            dependencies {
// ...
                implementation(libs.kotlinx.serialization.json)     // <----
            }
        }
    }
}
```



Most of the problem here is the (usual) catastrophic mess surrounding gradle. It's beyond me why a great product (kotlin) has to depend on it. It would be best to expect/assume that the end users are clueless about gradle and therefore be extra careful documenting the installation instructions.
