### ISSUE TITLE
Cannot properly install KxS

### ISSUE THREAD

**Issue by WarningImHack3r** [Kotlin/kotlinx.serialization#2710]
**Describe the bug**

Based on https://github.com/JetBrains/intellij-platform-plugin-template, I'm trying to use kotlinx.serialization for a plugin. However, despite multiple attempts with different configurations, I cannot make the plugin to get installed properly: my setup seems to be using an old KxS bundled with Kotlin instead of the one I'm telling it to use.

I tried entirely cleaning my Gradle cache, restarting the IDE, re-building from scratch without cache, hardcoding the dependencies in my `kts` file... (I've been trying for multiple previous Gradle versions too)

**To Reproduce**

Use this `libs.versions.toml` (truncated for brevity):
```toml
[versions]
kotlin = "1.9.24"
serializationJson = "1.6.3"

[libraries]
serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "plugin.serialization", version.ref = "kotlin" }
```

and this `build.gradle.kts` (truncated for brevity):
```kts
plugins {
    id("java") // Java support
    alias(libs.plugins.kotlin) // Kotlin support
    kotlin(libs.plugins.serialization.get().pluginId) version libs.versions.kotlin // Kotlin Serialization support
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation(libs.serializationJson)
}

kotlin {
    jvmToolchain(11)
}
```

**Expected behavior**

To use the version of the library I want it to use (1.6.3 here)

**Environment**
 - Kotlin version: [e.g. 1.3.30] 1.9.24
 - Library version: [e.g. 0.11.0] 1.9.24/1.6.3
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations] JVM
 - Gradle version: [e.g. 4.10] 8.8
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4] IDEA U 2024.1.2
 - Other relevant context [e.g. OS version, JRE version, ... ] macOS 14.5, JDK 11
